---
- name: Add 'vaultwarden' user
  user:
    name: vaultwarden
    groups:
      - sudo
      - docker
    append: yes
    state: present
    shell: /bin/bash
    createhome: yes

- name: Create volume directories if it does not exist
  file:
    path: /home/vaultwarden/data/
    state: directory
    recurse: yes
    owner: vaultwarden
    group: vaultwarden

- name: Deploy stack from base compose file and override the web service
  become: yes
  become_user: vaultwarden
  docker_stack:
    state: present
    name: vaultwarden
    compose:
      - version: "3"
        services:
          vaultwarden:
            image: vaultwarden/server:latest
            restart: always
            volumes:
              - /home/vaultwarden/data/:/data/
            ports:
              - "80:80"
