---
- name: Install libs for docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

- name: Add signing key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add repository into sources list
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker
  apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
      - python3-pip
      - python3-jsondiff
    state: latest
    update_cache: true

- name: Add 'docker' group
  group:
    name: docker
    state: present

- name: Add 'docker' group to main user
  user:
    name: "{{ sys.user }}"
    groups:
      docker
    append: yes


- name: Make sure docker python module is installed
  pip:
    name: docker
